import { Truck, Wrench, ShieldCheck, Boxes } from "lucide-react";

// --- Products ---------------------------------------------------------------
// NOTE:
// - Use this as website starter content.
// - Verify each P/N with your pricelist/EPC before quoting customers.
// - Product images are expected in /public/products using the exact part number as filename.
//   Example: /public/products/16510-61J00-000.jpg
// - If an image file does not exist yet, the UI should fallback to makePlaceholder(code).

export const MODELS_APV = ["APV"];
export const MODELS_NEW_CARRY = ["New Carry"];
export const MODELS_ERTIGA_XL7 = ["All New Ertiga", "XL7"];

export const makePlaceholder = (code: string) =>
  `data:image/svg+xml;utf8,${encodeURIComponent(`
    <svg xmlns="http://www.w3.org/2000/svg" width="1200" height="800" viewBox="0 0 1200 800">
      <rect width="1200" height="800" fill="#f3f4f6"/>
      <rect x="40" y="40" width="1120" height="720" rx="24" fill="#e5e7eb" stroke="#d1d5db"/>
      <text x="600" y="330" text-anchor="middle" font-family="Arial, sans-serif" font-size="42" fill="#374151">
        Suzuki Genuine Part
      </text>
      <text x="600" y="410" text-anchor="middle" font-family="Arial, sans-serif" font-size="30" fill="#6b7280">
        ${code}
      </text>
      <text x="600" y="470" text-anchor="middle" font-family="Arial, sans-serif" font-size="22" fill="#9ca3af">
        Image placeholder
      </text>
    </svg>
  `)}`;

export const getProductImage = (code: string) => `/products/${code}.jpg`;

export const PRODUCTS = [
  // APV
  {
    id: 1,
    brand: "suzuki",
    category: "Filters",
    code: "16510-61J00-000",
    name: "Oil Filter",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("16510-61J00-000"),
  },
  {
    id: 2,
    brand: "suzuki",
    category: "Suspension",
    code: "41601-61J00-000",
    name: "Front Shock Absorber RH",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("41601-61J00-000"),
  },
  {
    id: 3,
    brand: "suzuki",
    category: "Suspension",
    code: "41602-61J00-000",
    name: "Front Shock Absorber LH",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("41602-61J00-000"),
  },
  {
    id: 4,
    brand: "suzuki",
    category: "Suspension",
    code: "41700-61J00-000",
    name: "Front Coil Spring (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("41700-61J00-000"),
  },
  {
    id: 5,
    brand: "suzuki",
    category: "Engine",
    code: "15100-60K03-000",
    name: "Oil Pump Assembly (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("15100-60K03-000"),
  },
  {
    id: 6,
    brand: "suzuki",
    category: "Braking",
    code: "45200-61J00-000",
    name: "Front Brake Component (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("45200-61J00-000"),
  },
  {
    id: 7,
    brand: "suzuki",
    category: "Engine",
    code: "12761-71C20-000",
    name: "Engine Valve / Timing Component (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("12761-71C20-000"),
  },
  {
    id: 8,
    brand: "suzuki",
    category: "Engine",
    code: "17521-86550-000",
    name: "Cooling / Radiator Hose Component (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("17521-86550-000"),
  },
  {
    id: 9,
    brand: "suzuki",
    category: "Engine",
    code: "95141-61J10-000",
    name: "Drive Belt (Verify size / use)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("95141-61J10-000"),
  },
  {
    id: 10,
    brand: "suzuki",
    category: "Engine",
    code: "95141-61J20-000",
    name: "Drive Belt (Verify size / use)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("95141-61J20-000"),
  },
  {
    id: 11,
    brand: "suzuki",
    category: "Steering",
    code: "45341-61J00-000",
    name: "Tie Rod End / Steering Link (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("45341-61J00-000"),
  },
  {
    id: 12,
    brand: "suzuki",
    category: "Suspension",
    code: "42412-61J00-000",
    name: "Front Hub / Bearing Component (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("42412-61J00-000"),
  },
  {
    id: 13,
    brand: "suzuki",
    category: "Suspension",
    code: "41333-61J00-000",
    name: "Front Suspension Mount / Seat (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("41333-61J00-000"),
  },
  {
    id: 14,
    brand: "suzuki",
    category: "Suspension",
    code: "48810-61J10-000",
    name: "Stabilizer Link / Rod (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("48810-61J10-000"),
  },
  {
    id: 15,
    brand: "suzuki",
    category: "Suspension",
    code: "48830-61J00-000",
    name: "Stabilizer Bushing / Link Component (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("48830-61J00-000"),
  },
  {
    id: 16,
    brand: "suzuki",
    category: "Suspension",
    code: "48830-61J20-000",
    name: "Stabilizer Bushing / Link Component (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("48830-61J20-000"),
  },
  {
    id: 17,
    brand: "suzuki",
    category: "Engine",
    code: "09289-05013-000",
    name: "Seal / O-Ring / Washer (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("09289-05013-000"),
  },
  {
    id: 18,
    brand: "suzuki",
    category: "Transmission",
    code: "22000-60K00-000",
    name: "Clutch Cover Set",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("22000-60K00-000"),
  },
  {
    id: 19,
    brand: "suzuki",
    category: "Filters",
    code: "13780-61J00-000",
    name: "Air Filter Element",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("13780-61J00-000"),
  },
  {
    id: 20,
    brand: "suzuki",
    category: "Engine",
    code: "11189-71C00-000",
    name: "Engine Gasket (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("11189-71C00-000"),
  },
  {
    id: 21,
    brand: "suzuki",
    category: "Engine",
    code: "12111-61J10-0A0",
    name: "Cylinder Head / Engine Head Component (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("12111-61J10-0A0"),
  },
  {
    id: 22,
    brand: "suzuki",
    category: "Engine",
    code: "12111-61J10-050",
    name: "Cylinder Head / Engine Head Component (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("12111-61J10-050"),
  },
  {
    id: 23,
    brand: "suzuki",
    category: "Engine",
    code: "12140-61J00-000",
    name: "Cylinder Head Gasket (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("12140-61J00-000"),
  },
  {
    id: 24,
    brand: "suzuki",
    category: "Engine",
    code: "12140-61J00-050",
    name: "Cylinder Head Gasket (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("12140-61J00-050"),
  },
  {
    id: 25,
    brand: "suzuki",
    category: "Suspension",
    code: "48531-61J70-000",
    name: "Rear Shock Absorber RH (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("48531-61J70-000"),
  },
  {
    id: 26,
    brand: "suzuki",
    category: "Suspension",
    code: "48550-61J70-000",
    name: "Rear Shock Absorber / Spring Component (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("48550-61J70-000"),
  },
  {
    id: 27,
    brand: "suzuki",
    category: "Transmission",
    code: "22400-60K00-000",
    name: "Clutch Release Bearing",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("22400-60K00-000"),
  },
  {
    id: 28,
    brand: "suzuki",
    category: "Transmission",
    code: "22100-60K00-000",
    name: "Clutch Disc",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("22100-60K00-000"),
  },
  {
    id: 29,
    brand: "suzuki",
    category: "Transmission",
    code: "23265-60K00-000",
    name: "Clutch Cable / Clutch Control Component (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("23265-60K00-000"),
  },
  {
    id: 30,
    brand: "suzuki",
    category: "Electrical",
    code: "33400-62J00-000",
    name: "Ignition Coil",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("33400-62J00-000"),
  },
  {
    id: 31,
    brand: "suzuki",
    category: "Electrical",
    code: "35120-61J00-000",
    name: "Ignition Switch",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("35120-61J00-000"),
  },
  {
    id: 32,
    brand: "suzuki",
    category: "Electrical",
    code: "35320-61J00-000",
    name: "Brake / Stop Lamp Switch",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("35320-61J00-000"),
  },
  {
    id: 33,
    brand: "suzuki",
    category: "Body & Trim",
    code: "35650-61J00-000",
    name: "Door Handle / Door Lock Component RH (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("35650-61J00-000"),
  },
  {
    id: 34,
    brand: "suzuki",
    category: "Body & Trim",
    code: "35670-61J00-000",
    name: "Door Handle / Door Lock Component LH (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("35670-61J00-000"),
  },
  {
    id: 35,
    brand: "suzuki",
    category: "Body & Trim",
    code: "35650-60K00-000",
    name: "Door Handle / Door Lock Component RH (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("35650-60K00-000"),
  },
  {
    id: 36,
    brand: "suzuki",
    category: "Body & Trim",
    code: "35670-60K00-000",
    name: "Door Handle / Door Lock Component LH (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("35670-60K00-000"),
  },
  {
    id: 37,
    brand: "suzuki",
    category: "Transmission",
    code: "23710-61J21-000",
    name: "Gear Shift / Clutch Control Component (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("23710-61J21-000"),
  },
  {
    id: 38,
    brand: "suzuki",
    category: "Transmission",
    code: "23710-60K20-000",
    name: "Gear Shift / Clutch Control Component (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("23710-60K20-000"),
  },
  {
    id: 39,
    brand: "suzuki",
    category: "Electrical",
    code: "33705-66D00-000",
    name: "Bulb / Lamp Component (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("33705-66D00-000"),
  },
  {
    id: 40,
    brand: "suzuki",
    category: "Braking",
    code: "43511-61J02-000",
    name: "Brake Pad / Disc Brake Component (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("43511-61J02-000"),
  },
  {
    id: 41,
    brand: "suzuki",
    category: "Suspension",
    code: "55210-61J00-000",
    name: "Control Arm / Suspension Arm (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("55210-61J00-000"),
  },
  {
    id: 42,
    brand: "suzuki",
    category: "Steering",
    code: "53200-61J00-000",
    name: "Steering Gear / Rack Assembly",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("53200-61J00-000"),
  },
  {
    id: 43,
    brand: "suzuki",
    category: "Suspension",
    code: "55311-61J01-000",
    name: "Suspension Member / Arm Component (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("55311-61J01-000"),
  },
  {
    id: 44,
    brand: "suzuki",
    category: "Body & Trim",
    code: "71721-60K00-5PK",
    name: "Bumper Bracket / Garnish (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("71721-60K00-5PK"),
  },
  {
    id: 45,
    brand: "suzuki",
    category: "Body & Trim",
    code: "72111-61J00-5PK",
    name: "Door / Opening Weatherstrip (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("72111-61J00-5PK"),
  },
  {
    id: 46,
    brand: "suzuki",
    category: "Body & Trim",
    code: "71811-61J00-5PK",
    name: "Bumper Face / Panel (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("71811-61J00-5PK"),
  },
  {
    id: 47,
    brand: "suzuki",
    category: "Body & Trim",
    code: "71711-61J00-799",
    name: "Front Bumper / Spoiler Component (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("71711-61J00-799"),
  },
  {
    id: 48,
    brand: "suzuki",
    category: "Body & Trim",
    code: "71712-61J00-5PK",
    name: "Bumper Garnish (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("71712-61J00-5PK"),
  },
  {
    id: 49,
    brand: "suzuki",
    category: "Body & Trim",
    code: "83410-61J00-000",
    name: "Seat Trim / Seat Cushion Component (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("83410-61J00-000"),
  },
  {
    id: 50,
    brand: "suzuki",
    category: "Body & Trim",
    code: "83440-61J00-000",
    name: "Seat Trim / Seat Back Component (Verify description)",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("83440-61J00-000"),
  },
  {
    id: 51,
    brand: "suzuki",
    category: "Engine",
    code: "09482-00740-000",
    name: "Spark Plug",
    oem: true,
    models: MODELS_APV,
    image: getProductImage("09482-00740-000"),
  },

  // New Carry
  {
    id: 52,
    brand: "suzuki",
    category: "Transmission",
    code: "22000-52S00-000",
    name: "Clutch Cover Set",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("22000-52S00-000"),
  },
  {
    id: 53,
    brand: "suzuki",
    category: "Transmission",
    code: "22100-52S00-000",
    name: "Clutch Disc",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("22100-52S00-000"),
  },
  {
    id: 54,
    brand: "suzuki",
    category: "Transmission",
    code: "22100-52S01-000",
    name: "Clutch Disc (Revision)",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("22100-52S01-000"),
  },
  {
    id: 55,
    brand: "suzuki",
    category: "Transmission",
    code: "22400-52S00-000",
    name: "Clutch Release Bearing",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("22400-52S00-000"),
  },
  {
    id: 56,
    brand: "suzuki",
    category: "Transmission",
    code: "22400-52S02-000",
    name: "Clutch Release Bearing (Revision)",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("22400-52S02-000"),
  },
  {
    id: 57,
    brand: "suzuki",
    category: "Transmission",
    code: "23265-64PA1-000",
    name: "Clutch Cable / Clutch Control Component (Verify description)",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("23265-64PA1-000"),
  },
  {
    id: 58,
    brand: "suzuki",
    category: "Transmission",
    code: "23710-52S20-000",
    name: "Gear Shift / Clutch Control Component (Verify description)",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("23710-52S20-000"),
  },
  {
    id: 59,
    brand: "suzuki",
    category: "Engine",
    code: "12934-77M00-000",
    name: "Valve Shim / Valve Train Component (Verify description)",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("12934-77M00-000"),
  },
  {
    id: 60,
    brand: "suzuki",
    category: "Engine",
    code: "11189-74L00-000",
    name: "Engine Gasket (Verify description)",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("11189-74L00-000"),
  },
  {
    id: 61,
    brand: "suzuki",
    category: "Suspension",
    code: "41601-52S00-000",
    name: "Front Shock Absorber RH",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("41601-52S00-000"),
  },
  {
    id: 62,
    brand: "suzuki",
    category: "Suspension",
    code: "41602-52S00-000",
    name: "Front Shock Absorber LH",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("41602-52S00-000"),
  },
  {
    id: 63,
    brand: "suzuki",
    category: "Body & Trim",
    code: "55810-52S00-000",
    name: "Muffler / Exhaust Bracket Component (Verify description)",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("55810-52S00-000"),
  },
  {
    id: 64,
    brand: "suzuki",
    category: "Steering",
    code: "53200-52S00-000",
    name: "Steering Gear / Rack Assembly",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("53200-52S00-000"),
  },
  {
    id: 65,
    brand: "suzuki",
    category: "Electrical",
    code: "35120-52S00-000",
    name: "Ignition Switch",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("35120-52S00-000"),
  },
  {
    id: 66,
    brand: "suzuki",
    category: "Electrical",
    code: "35320-52S00-000",
    name: "Brake / Stop Lamp Switch",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("35320-52S00-000"),
  },
  {
    id: 67,
    brand: "suzuki",
    category: "Body & Trim",
    code: "71721-52S00-5PK",
    name: "Bumper Bracket / Garnish (Verify description)",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("71721-52S00-5PK"),
  },
  {
    id: 68,
    brand: "suzuki",
    category: "Body & Trim",
    code: "71721-52S50-5PK",
    name: "Bumper Bracket / Garnish (Verify description)",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("71721-52S50-5PK"),
  },
  {
    id: 69,
    brand: "suzuki",
    category: "Braking",
    code: "58310-52S01-000",
    name: "Rear Brake Component (Verify description)",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("58310-52S01-000"),
  },
  {
    id: 70,
    brand: "suzuki",
    category: "Braking",
    code: "58511-52S01-000",
    name: "Rear Brake Shoe / Lining Component (Verify description)",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("58511-52S01-000"),
  },
  {
    id: 71,
    brand: "suzuki",
    category: "Braking",
    code: "58611-52S01-000",
    name: "Rear Brake Hardware Component (Verify description)",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("58611-52S01-000"),
  },
  {
    id: 72,
    brand: "suzuki",
    category: "Body & Trim",
    code: "71711-52S00-5PK",
    name: "Front Bumper / Spoiler Component (Verify description)",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("71711-52S00-5PK"),
  },
  {
    id: 73,
    brand: "suzuki",
    category: "Body & Trim",
    code: "71711-52S50-5PK",
    name: "Front Bumper / Spoiler Component (Verify description)",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("71711-52S50-5PK"),
  },
  {
    id: 74,
    brand: "suzuki",
    category: "Suspension",
    code: "41700-52S01-000",
    name: "Front Coil Spring (Verify description)",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("41700-52S01-000"),
  },
  {
    id: 75,
    brand: "suzuki",
    category: "Braking",
    code: "45201-52S00-000",
    name: "Front Brake Component RH (Verify description)",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("45201-52S00-000"),
  },
  {
    id: 76,
    brand: "suzuki",
    category: "Braking",
    code: "45202-52S00-000",
    name: "Front Brake Component LH (Verify description)",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("45202-52S00-000"),
  },
  {
    id: 77,
    brand: "suzuki",
    category: "Engine",
    code: "16141-73R00-000",
    name: "Engine Gasket / Cooling Component (Verify description)",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("16141-73R00-000"),
  },
  {
    id: 78,
    brand: "suzuki",
    category: "Engine",
    code: "11342-67LD0-000",
    name: "Engine Cover / Housing Gasket (Verify description)",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("11342-67LD0-000"),
  },
  {
    id: 79,
    brand: "suzuki",
    category: "Engine",
    code: "12911-77M00-000",
    name: "Intake Valve (Verify description)",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("12911-77M00-000"),
  },
  {
    id: 80,
    brand: "suzuki",
    category: "Engine",
    code: "12915-77M00-000",
    name: "Exhaust Valve (Verify description)",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("12915-77M00-000"),
  },
  {
    id: 81,
    brand: "suzuki",
    category: "Engine",
    code: "09482-00L10-000",
    name: "Spark Plug",
    oem: true,
    models: MODELS_NEW_CARRY,
    image: getProductImage("09482-00L10-000"),
  },

  // All New Ertiga + XL7
  {
    id: 82,
    brand: "suzuki",
    category: "Body & Trim",
    code: "35603-73R10-000",
    name: "Door Handle / Lock Component RH Front (Verify description)",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("35603-73R10-000"),
  },
  {
    id: 83,
    brand: "suzuki",
    category: "Body & Trim",
    code: "35604-73R10-000",
    name: "Door Handle / Lock Component LH Front (Verify description)",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("35604-73R10-000"),
  },
  {
    id: 84,
    brand: "suzuki",
    category: "Body & Trim",
    code: "35701-73R10-000",
    name: "Door Latch / Lock Component RH Rear (Verify description)",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("35701-73R10-000"),
  },
  {
    id: 85,
    brand: "suzuki",
    category: "Body & Trim",
    code: "35702-73R10-000",
    name: "Door Latch / Lock Component LH Rear (Verify description)",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("35702-73R10-000"),
  },
  {
    id: 86,
    brand: "suzuki",
    category: "Body & Trim",
    code: "35661-73R00-000",
    name: "Door Opener / Handle Component RH (Verify description)",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("35661-73R00-000"),
  },
  {
    id: 87,
    brand: "suzuki",
    category: "Body & Trim",
    code: "35681-73R00-000",
    name: "Door Opener / Handle Component LH (Verify description)",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("35681-73R00-000"),
  },
  {
    id: 88,
    brand: "suzuki",
    category: "Electrical",
    code: "35120-73RB1-000",
    name: "Ignition Switch",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("35120-73RB1-000"),
  },
  {
    id: 89,
    brand: "suzuki",
    category: "Electrical",
    code: "35120-73RA1-000",
    name: "Ignition Switch",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("35120-73RA1-000"),
  },
  {
    id: 90,
    brand: "suzuki",
    category: "Electrical",
    code: "35320-73RA1-000",
    name: "Brake / Stop Lamp Switch",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("35320-73RA1-000"),
  },
  {
    id: 91,
    brand: "suzuki",
    category: "Electrical",
    code: "35320-73RB1-000",
    name: "Brake / Stop Lamp Switch",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("35320-73RB1-000"),
  },
  {
    id: 92,
    brand: "suzuki",
    category: "Body & Trim",
    code: "72110-86TB0-D3W",
    name: "Door Weatherstrip / Opening Seal (Verify description)",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("72110-86TB0-D3W"),
  },
  {
    id: 93,
    brand: "suzuki",
    category: "Steering",
    code: "57300-72SA2-000",
    name: "Steering Column Assembly (Verify description)",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("57300-72SA2-000"),
  },
  {
    id: 94,
    brand: "suzuki",
    category: "Steering",
    code: "57611-72SA0-000",
    name: "Steering Column Cover Upper (Verify description)",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("57611-72SA0-000"),
  },
  {
    id: 95,
    brand: "suzuki",
    category: "Steering",
    code: "57711-72SA0-000",
    name: "Steering Column Cover Lower (Verify description)",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("57711-72SA0-000"),
  },
  {
    id: 96,
    brand: "suzuki",
    category: "Braking",
    code: "43210-73R70-QC8",
    name: "Brake Booster / Master Component (Verify description)",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("43210-73R70-QC8"),
  },
  {
    id: 97,
    brand: "suzuki",
    category: "Body & Trim",
    code: "71711-72SA0-799",
    name: "Front Bumper / Spoiler Component (Verify description)",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("71711-72SA0-799"),
  },
  {
    id: 98,
    brand: "suzuki",
    category: "Body & Trim",
    code: "72330-73R20-5PK",
    name: "Door Glass Run / Weatherstrip Rear (Verify description)",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("72330-73R20-5PK"),
  },
  {
    id: 99,
    brand: "suzuki",
    category: "Body & Trim",
    code: "72320-73R00-000",
    name: "Door Glass Run / Weatherstrip RH (Verify description)",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("72320-73R00-000"),
  },
  {
    id: 100,
    brand: "suzuki",
    category: "Body & Trim",
    code: "72340-73R00-000",
    name: "Door Glass Run / Weatherstrip LH (Verify description)",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("72340-73R00-000"),
  },
  {
    id: 101,
    brand: "suzuki",
    category: "Body & Trim",
    code: "72321-72SA0-000",
    name: "Door Window Moulding RH (Verify description)",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("72321-72SA0-000"),
  },
  {
    id: 102,
    brand: "suzuki",
    category: "Body & Trim",
    code: "72322-72SA0-000",
    name: "Door Window Moulding LH (Verify description)",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("72322-72SA0-000"),
  },
  {
    id: 103,
    brand: "suzuki",
    category: "Braking",
    code: "45201-73R00-000",
    name: "Front Brake Component RH (Verify description)",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("45201-73R00-000"),
  },
  {
    id: 104,
    brand: "suzuki",
    category: "Braking",
    code: "45202-73R00-000",
    name: "Front Brake Component LH (Verify description)",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("45202-73R00-000"),
  },
  {
    id: 105,
    brand: "suzuki",
    category: "Electrical",
    code: "35120-73R11-000",
    name: "Ignition Switch",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("35120-73R11-000"),
  },
  {
    id: 106,
    brand: "suzuki",
    category: "Electrical",
    code: "35320-73R11-000",
    name: "Brake / Stop Lamp Switch",
    oem: true,
    models: MODELS_ERTIGA_XL7,
    image: getProductImage("35320-73R11-000"),
  },
];

// --- Testimonials -----------------------------------------------------------
export type Testimonial = {
  name: string;
  title_en: string;
  title_id: string;
  quote_en: string;
  quote_id: string;
  image?: string;
};

export const TESTIMONIALS: Testimonial[] = [
  {
    name: "Budi Santoso",
    title_en: "Owner, Mitra Motor Workshop",
    title_id: "Pemilik, Bengkel Mitra Motor",
    quote_en:
      "JMN is our #1 supplier. Their parts are always genuine, and the fulfillment accuracy saves us from costly delays. Their team is knowledgeable and incredibly responsive.",
    quote_id:
      "JMN adalah pemasok #1 kami. Suku cadangnya selalu asli, dan akurasi pemenuhannya menyelamatkan kami dari penundaan yang mahal. Tim mereka berpengetahuan luas dan sangat responsif.",
    image:
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=400&auto=format&fit=crop",
  },
  {
    name: "Ahmad Yani",
    title_en: "Lead Mechanic, Jaya Abadi Service",
    title_id: "Kepala Mekanik, Servis Jaya Abadi",
    quote_en:
      "The quality of Suzuki Genuine Parts from JMN is unmatched. Our customers notice the difference, and it has improved our workshop's reputation significantly.",
    quote_id:
      "Kualitas Suku Cadang Asli Suzuki dari JMN tidak ada tandingannya. Pelanggan kami merasakan perbedaannya, dan itu telah meningkatkan reputasi bengkel kami secara signifikan.",
    image:
      "https://images.unsplash.com/photo-1557862921-37829c790f19?q=80&w=400&auto=format&fit=crop",
  },
  {
    name: "Rina Wijaya",
    title_en: "Procurement Manager, Global Auto Exports",
    title_id: "Manajer Pengadaan, Global Auto Exports",
    quote_en:
      "For our international clients, JMN's export documentation is always perfect. They handle consolidation and logistics professionally, making them a reliable partner for global trade.",
    quote_id:
      "Untuk klien internasional kami, dokumentasi ekspor JMN selalu sempurna. Mereka menangani konsolidasi dan logistik secara profesional, menjadikan mereka mitra yang andal untuk perdagangan global.",
    image:
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=400&auto=format&fit=crop",
  },
  {
    name: "Adi Nugroho",
    title_en: "Procurement Lead, Nusantara Autoparts",
    title_id: "Kepala Pengadaan, Nusantara Autoparts",
    quote_en:
      "Great consolidation and fast response times. Export docs are always correct.",
    quote_id:
      "Konsolidasi rapi dan respon cepat. Dokumen ekspor selalu benar.",
  },
];

// --- Feature bullets used on “Why Us” --------------------------------------
export const FEATURE_ITEMS = [
  {
    icon: Truck,
    title: "Global Shipping",
    desc: "Export-ready logistics network reaching Asia, Middle East, Africa, and beyond.",
  },
  {
    icon: ShieldCheck,
    title: "100% Genuine Parts",
    desc: "OEM-certified parts with verifiable origin and consistent quality.",
  },
  {
    icon: Boxes,
    title: "Large Inventory",
    desc: "Extensive SKUs for Suzuki Genuine Parts plus Toyota, Daihatsu, Mitsubishi.",
  },
  {
    icon: Wrench,
    title: "Technical Support",
    desc: "Assistance for fitment compatibility and part number cross-references.",
  },
] as const;

// --- Stats displayed in Hero ------------------------------------------------
export type StatCard = { label: string; value: number; suffix?: string };

export const STAT_CARDS: StatCard[] = [
  { label: "Years in Trade", value: 12 },
  { label: "Active SKUs", value: 12000 },
  { label: "Countries Served", value: 22 },
  { label: "Fulfillment Accuracy", value: 99.5, suffix: "%" },
];

export const BRANDS = [
  { name: "Suzuki", key: "suzuki", logo: "/logos/logo_suzuki.svg" },
  { name: "Toyota", key: "toyota", logo: "/logos/logo_toyota.svg" },
  { name: "Daihatsu", key: "daihatsu", logo: "/logos/logo_daihatsu.svg" },
  { name: "Mitsubishi", key: "mitsubishi", logo: "/logos/logo_mitsubishi.svg" },
] as const;

export type Brand = (typeof BRANDS)[number];