"use client";
import * as React from "react";

export type Lang = "en" | "id" | "vi" | "ar" | "th";

export const LangContext = React.createContext<Lang>("en");

export const LANGS: Array<{ code: Lang; label: string; flag: string; dir: "ltr" | "rtl" }> = [
  { code: "en", label: "English",   flag: "🇬🇧", dir: "ltr" },
  { code: "id", label: "Indonesia", flag: "🇮🇩", dir: "ltr" },
  { code: "vi", label: "Tiếng Việt",flag: "🇻🇳", dir: "ltr" },
  { code: "ar", label: "العربية",   flag: "🇸🇦", dir: "rtl" },
  { code: "th", label: "ไทย",       flag: "🇹🇭", dir: "ltr" },
];

export const getDir = (lang: Lang) => LANGS.find(l => l.code === lang)?.dir ?? "ltr";

// ── Translations ────────────────────────────────────────────────────────────────
const STR = {
  en: {
    brand_line: "JMN • Suzuki Genuine Parts Distributor",
    hero_title: "Trusted OEM Auto Parts for Indonesia & the World",
    hero_desc: "We are PT. Jaya Makmur Nugraha (JMN) — Indonesia's main distributor of Suzuki Genuine Parts, also supplying Toyota, Daihatsu, and Mitsubishi.",
    browse_products: "Browse Products",
    get_quote: "Get a Quote",
    nav_products: "Products",
    nav_why: "Why Us",
    nav_export: "Global Export",
    nav_contact: "Contact",
    products_title: "Product Catalog",
    products_sub: "Browse highlights from our multi-brand inventory. Full catalog available on request.",
    quick_filters: "Filters",
    request_full_catalog: "Request full catalog",
    download_brochure: "Download brochure (PDF)",
    why_title: "Why work with JMN?",
    why_desc: "As the main distributor of Suzuki Genuine Parts in Indonesia, we combine deep OEM relationships with lean fulfillment and global export capability.",
    export_title: "Global Export Capability",
    export_desc: "We ship worldwide with full export documentation tailored to your Incoterms.",
    export_b1: "Multi-brand consolidation (Suzuki, Toyota, Daihatsu, Mitsubishi)",
    export_b2: "Air & Sea freight options (LCL/FCL)",
    export_b3: "Proforma Invoice, Packing List, COO, and other export docs",
    discuss_shipment: "Discuss your shipment",
    contact_title: "Contact Us",
    contact_desc: "Tell us your required part numbers, quantities, destination, and timeline. Our sales team will reply within 1 business day.",
    contact_name: "Your name",
    contact_email: "Email",
    contact_message: "Message",
    contact_send: "Send via Email",
    contact_chat: "Chat on WhatsApp",
    faq_fast: "What information helps us quote faster?",
    faq_fast_a: "Part numbers (OEM if possible), vehicle model/year, target quantities, destination port, preferred Incoterms, and required lead time.",
    faq_ship: "Do you ship internationally?",
    faq_ship_a: "Yes — we dispatch globally with export documentation and multiple forwarders (air & sea).",
    our_location: "Our Location",
    view_on_maps: "View on Google Maps",
    testimonials_title: "What Our Partners Say",
    testimonials_sub: "Real stories from workshops and distributors who trust JMN.",
  },
  id: {
    brand_line: "JMN • Distributor Resmi Suku Cadang Suzuki",
    hero_title: "Suku Cadang OEM Tepercaya untuk Indonesia & Dunia",
    hero_desc: "Kami PT. Jaya Makmur Nugraha (JMN) — distributor utama Suzuki Genuine Parts di Indonesia, juga memasok Toyota, Daihatsu, dan Mitsubishi.",
    browse_products: "Lihat Produk",
    get_quote: "Minta Penawaran",
    nav_products: "Produk",
    nav_why: "Mengapa Kami",
    nav_export: "Ekspor Global",
    nav_contact: "Kontak",
    products_title: "Katalog Produk",
    products_sub: "Koleksi unggulan dari inventori multi-brand kami. Katalog lengkap tersedia atas permintaan.",
    quick_filters: "Filter",
    request_full_catalog: "Minta katalog lengkap",
    download_brochure: "Unduh brosur (PDF)",
    why_title: "Mengapa memilih JMN?",
    why_desc: "Sebagai distributor utama Suzuki Genuine Parts di Indonesia, kami memadukan hubungan OEM yang kuat dengan pemenuhan efisien dan kemampuan ekspor global.",
    export_title: "Kemampuan Ekspor Global",
    export_desc: "Kami kirim ke seluruh dunia dengan dokumen ekspor lengkap sesuai Incoterms Anda.",
    export_b1: "Konsolidasi multi-brand (Suzuki, Toyota, Daihatsu, Mitsubishi)",
    export_b2: "Opsi kargo udara & laut (LCL/FCL)",
    export_b3: "Proforma Invoice, Packing List, COO, dan dokumen ekspor lainnya",
    discuss_shipment: "Diskusikan pengiriman Anda",
    contact_title: "Hubungi Kami",
    contact_desc: "Sebutkan nomor part, kuantitas, tujuan, dan timeline. Balasan ≤ 1 hari kerja.",
    contact_name: "Nama Anda",
    contact_email: "Email",
    contact_message: "Pesan",
    contact_send: "Kirim via Email",
    contact_chat: "Chat di WhatsApp",
    faq_fast: "Data apa yang mempercepat penawaran?",
    faq_fast_a: "Nomor part (lebih baik OEM), model/tahun kendaraan, kuantitas, pelabuhan tujuan, Incoterms, dan lead time.",
    faq_ship: "Apakah bisa kirim internasional?",
    faq_ship_a: "Bisa — kami kirim global dengan dokumen ekspor dan beberapa forwarder (udara & laut).",
    our_location: "Lokasi Kami",
    view_on_maps: "Lihat di Google Maps",
    testimonials_title: "Kata Mitra Kami",
    testimonials_sub: "Kisah nyata dari bengkel dan distributor yang memercayai JMN.",
  },
  vi: {
    brand_line: "JMN • Nhà phân phối phụ tùng Suzuki chính hãng",
    hero_title: "Phụ tùng OEM đáng tin cậy cho Indonesia & Thế giới",
    hero_desc: "Chúng tôi là PT. Jaya Makmur Nugraha (JMN) — nhà phân phối chính phụ tùng Suzuki tại Indonesia, đồng thời cung cấp Toyota, Daihatsu và Mitsubishi.",
    browse_products: "Xem sản phẩm",
    get_quote: "Yêu cầu báo giá",
    nav_products: "Sản phẩm",
    nav_why: "Vì sao chọn chúng tôi",
    nav_export: "Xuất khẩu",
    nav_contact: "Liên hệ",
    products_title: "Danh mục sản phẩm",
    products_sub: "Các sản phẩm tiêu biểu trong kho đa thương hiệu. Danh mục đầy đủ theo yêu cầu.",
    quick_filters: "Bộ lọc",
    request_full_catalog: "Yêu cầu danh mục đầy đủ",
    download_brochure: "Tải brochure (PDF)",
    why_title: "Vì sao làm việc với JMN?",
    why_desc: "Là nhà phân phối chính phụ tùng Suzuki tại Indonesia, JMN có quan hệ OEM sâu rộng, thực hiện tinh gọn và năng lực xuất khẩu toàn cầu.",
    export_title: "Năng lực xuất khẩu toàn cầu",
    export_desc: "Chúng tôi giao hàng đi khắp thế giới với đầy đủ chứng từ theo Incoterms của bạn.",
    export_b1: "Hợp nhất đa thương hiệu (Suzuki, Toyota, Daihatsu, Mitsubishi)",
    export_b2: "Vận chuyển đường không & biển (LCL/FCL)",
    export_b3: "PI, Packing List, COO và chứng từ xuất khẩu khác",
    discuss_shipment: "Trao đổi lô hàng",
    contact_title: "Liên hệ",
    contact_desc: "Hãy cho chúng tôi mã phụ tùng, số lượng, điểm đến và thời gian. Chúng tôi phản hồi trong 1 ngày làm việc.",
    contact_name: "Tên của bạn",
    contact_email: "Email",
    contact_message: "Nội dung",
    contact_send: "Gửi Email",
    contact_chat: "Chat WhatsApp",
    faq_fast: "Thông tin nào giúp báo giá nhanh hơn?",
    faq_fast_a: "Mã phụ tùng, mẫu/năm xe, số lượng, cảng đến, Incoterms ưu tiên và thời gian giao hàng.",
    faq_ship: "Có giao quốc tế không?",
    faq_ship_a: "Có — chúng tôi giao toàn cầu với chứng từ xuất khẩu đầy đủ.",
    our_location: "Địa chỉ của chúng tôi",
    view_on_maps: "Xem trên Google Maps",
    testimonials_title: "Khách hàng nói gì",
    testimonials_sub: "Câu chuyện thực từ các gara và nhà phân phối tin dùng JMN.",
  },
  ar: {
    brand_line: "جي إم إن • موزّع قطع سوزوكي الأصلية",
    hero_title: "قطع غيار OEM موثوقة لإندونيسيا والعالم",
    hero_desc: "نحن PT. Jaya Makmur Nugraha (JMN) — الموزع الرئيسي لقطع سوزوكي الأصلية في إندونيسيا ونزوّد أيضاً تويوتا ودايهاتسو وميتسوبيشي.",
    browse_products: "تصفح المنتجات",
    get_quote: "اطلب عرض سعر",
    nav_products: "المنتجات",
    nav_why: "لماذا نحن",
    nav_export: "التصدير العالمي",
    nav_contact: "تواصل معنا",
    products_title: "كتالوج المنتجات",
    products_sub: "تعرّف على أبرز منتجات مخزوننا متعدد العلامات. الكتالوج الكامل عند الطلب.",
    quick_filters: "فلاتر",
    request_full_catalog: "طلب الكتالوج الكامل",
    download_brochure: "تنزيل الكتيّب (PDF)",
    why_title: "لماذا العمل مع JMN؟",
    why_desc: "بصفتنا الموزّع الرئيسي لقطع سوزوكي في إندونيسيا، نجمع بين علاقات OEM عميقة وتنفيذ مرن وقدرات تصدير عالمية.",
    export_title: "قدرات التصدير العالمية",
    export_desc: "نرسل إلى جميع أنحاء العالم مع مستندات تصدير كاملة وفق Incoterms الخاصة بك.",
    export_b1: "تجميع متعدد العلامات (Suzuki وToyota وDaihatsu وMitsubishi)",
    export_b2: "الشحن الجوي والبحري (LCL/FCL)",
    export_b3: "فاتورة أولية وقائمة تعبئة وشهادة منشأ ومستندات أخرى",
    discuss_shipment: "ناقش شحنتك",
    contact_title: "تواصل معنا",
    contact_desc: "أرسل أرقام القطع والكميات والوجهة والمدة المطلوبة. سنرد خلال يوم عمل واحد.",
    contact_name: "اسمك",
    contact_email: "البريد الإلكتروني",
    contact_message: "الرسالة",
    contact_send: "إرسال عبر البريد",
    contact_chat: "الدردشة عبر واتساب",
    faq_fast: "ما المعلومات التي تساعدنا على التسعير أسرع؟",
    faq_fast_a: "أرقام القطع، طراز/سنة المركبة، الكميات، ميناء الوجهة، Incoterms، ووقت التسليم المطلوب.",
    faq_ship: "هل تشحنون دولياً؟",
    faq_ship_a: "نعم — نشحن عالمياً مع مستندات التصدير ووسطاء شحن متعددين.",
    our_location: "موقعنا",
    view_on_maps: "عرض على خرائط Google",
    testimonials_title: "ماذا يقول شركاؤنا",
    testimonials_sub: "قصص حقيقية من ورش الت整يب والموزعين الذين يثقون بـ JMN.",
  },
  th: {
    brand_line: "JMN • ผู้จัดจำหน่ายอะไหล่ Suzuki แท้",
    hero_title: "อะไหล่ OEM ที่เชื่อถือได้ สำหรับอินโดนีเซียและทั่วโลก",
    hero_desc: "เราเป็น PT. Jaya Makmur Nugraha (JMN) — ผู้จัดจำหน่ายหลักอะไหล่ Suzuki แท้ในอินโดนีเซีย และยังจำหน่าย Toyota, Daihatsu, Mitsubishi",
    browse_products: "ดูสินค้า",
    get_quote: "ขอใบเสนอราคา",
    nav_products: "สินค้า",
    nav_why: "ทำไมต้องเรา",
    nav_export: "การส่งออก",
    nav_contact: "ติดต่อ",
    products_title: "แคตตาล็อกสินค้า",
    products_sub: "สินค้าเด่นจากคลังหลายแบรนด์ แคตตาล็อกฉบับเต็มมีให้ตามคำขอ",
    quick_filters: "ตัวกรอง",
    request_full_catalog: "ขอแคตตาล็อกฉบับเต็ม",
    download_brochure: "ดาวน์โหลดโบรชัวร์ (PDF)",
    why_title: "ทำไมต้องทำงานกับ JMN?",
    why_desc: "ในฐานะผู้จัดจำหน่ายหลักอะไหล่ Suzuki แท้ในอินโดนีเซีย เรามีความสัมพันธ์กับ OEM เข้มแข็ง พร้อมการส่งออกทั่วโลก",
    export_title: "ศักยภาพการส่งออกระดับโลก",
    export_desc: "เราจัดส่งทั่วโลก พร้อมเอกสารการส่งออกครบถ้วนตาม Incoterms ของคุณ",
    export_b1: "รวมหลายแบรนด์ (Suzuki, Toyota, Daihatsu, Mitsubishi)",
    export_b2: "ขนส่งทางอากาศ/ทางเรือ (LCL/FCL)",
    export_b3: "PI, Packing List, COO และเอกสารอื่น ๆ",
    discuss_shipment: "คุยรายละเอียดการส่งออก",
    contact_title: "ติดต่อเรา",
    contact_desc: "บอกหมายเลขอะไหล่ ปริมาณ ปลายทาง และระยะเวลา ทีมขายตอบกลับภายใน 1 วันทำการ",
    contact_name: "ชื่อของคุณ",
    contact_email: "อีเมล",
    contact_message: "ข้อความ",
    contact_send: "ส่งอีเมล",
    contact_chat: "แชทผ่าน WhatsApp",
    faq_fast: "ข้อมูลใดช่วยให้เสนอราคาเร็วขึ้น?",
    faq_fast_a: "หมายเลขอะไหล่ รุ่น/ปีรถ ปริมาณ ท่าเรือปลายทาง Incoterms และเวลาจัดส่งที่ต้องการ",
    faq_ship: "มีจัดส่งระหว่างประเทศหรือไม่?",
    faq_ship_a: "มี — เราจัดส่งทั่วโลกพร้อมเอกสารส่งออกครบถ้วน",
    our_location: "ที่ตั้งของเรา",
    view_on_maps: "ดูบน Google Maps",
    testimonials_title: "เสียงจากพาร์ทเนอร์",
    testimonials_sub: "เรื่องจริงจากอู่และผู้จัดจำหน่ายที่ไว้วางใจ JMN",
  },
} as const;

export const useT = () => {
  const lang = React.useContext(LangContext);
  return (k: keyof typeof STR["en"]) => (STR[lang]?.[k] ?? STR.en[k] ?? String(k));
};
