"use client";

import * as React from "react";
import { DEFAULT_LANG, LANGS, type Lang } from "@/lib/i18n";

export type { Lang } from "@/lib/i18n";

export const LangContext = React.createContext<Lang>(DEFAULT_LANG);

// Translations used by the homepage and shared site chrome.
const STR = {
  en: {
    brand_line: "JMN • Suzuki Genuine Parts Distributor",
    hero_title: "Trusted OEM Auto Parts for Indonesia & the World",
    hero_desc: "We are PT. Jaya Makmur Nugraha (JMN) — Indonesia's main distributor of Suzuki Genuine Parts, also supplying Toyota, Daihatsu, and Mitsubishi.",
    browse_products: "Browse Products",
    get_quote: "Get a Quote",
    hero_search_placeholder: "Search part number, model, or category...",
    hero_search_button: "Search",
    nav_products: "Products",
    nav_why: "Why Us",
    nav_export: "Global Export",
    nav_blog: "Blog",
    nav_contact: "Contact",
    products_title: "Product Catalog",
    products_sub: "Browse highlights from our multi-brand inventory. Full catalog available on request.",
    quick_filters: "Filters",
    request_full_catalog: "Request full catalog",
    download_brochure: "Download brochure (PDF)",
    why_title: "Why work with JMN?",
    why_desc: "As the main distributor of Suzuki Genuine Parts in Indonesia, we combine deep OEM relationships with lean fulfillment and global export capability.",
    export_title: "Global Export Capability",
    export_desc: "We ship worldwide with full export documentation tailored to your Incoterms.",
    export_b1: "Multi-brand consolidation (Suzuki, Toyota, Daihatsu, Mitsubishi)",
    export_b2: "Air & Sea freight options (LCL/FCL)",
    export_b3: "Proforma Invoice, Packing List, COO, and other export docs",
    discuss_shipment: "Discuss your shipment",
    contact_title: "Contact Us",
    contact_desc: "Tell us your required part numbers, quantities, destination, and timeline. Our sales team will reply within 1 business day.",
    contact_name: "Your name",
    contact_email: "Email",
    contact_message: "Message",
    contact_send: "Send via Email",
    contact_chat: "Chat on WhatsApp",
    faq_fast: "What information helps us quote faster?",
    faq_fast_a: "Part numbers (OEM if possible), vehicle model/year, target quantities, destination port, preferred Incoterms, and required lead time.",
    faq_ship: "Do you ship internationally?",
    faq_ship_a: "Yes — we dispatch globally with export documentation and multiple forwarders (air & sea).",
    faq_howbuy: "How do I buy spare parts from JMN?",
    faq_howbuy_a: "Send us your part numbers or vehicle model via WhatsApp or the contact form. We confirm stock and price, issue a Proforma Invoice, and ship once payment terms are agreed.",
    faq_moq: "Is there a minimum order quantity (MOQ) for export?",
    faq_moq_a: "We accommodate both small trial orders and full-container export orders. Let us know your target volume and we'll advise the most cost-effective shipping option.",
    faq_countries: "Which countries do you export spare parts to?",
    faq_countries_a: "We regularly export Suzuki genuine parts to the Middle East, Africa, and Southeast Asia, with experience shipping to 22+ countries.",
    our_location: "Our Location",
    view_on_maps: "View on Google Maps",
    testimonials_title: "What Our Partners Say",
    testimonials_sub: "Real stories from workshops and distributors who trust JMN.",
    about_label: "About Us",
    product_label: "Product Catalog",
    testimonials_label: "Testimonials",
    export_label: "Export & Shipping",
    contact_label: "Contact Us",
    location_label: "Our Location",
    export_lanes_title: "Trusted export lanes",
    hero_intro_cta: "Why JMN?",
    stat_years: "Years in Trade",
    stat_skus: "Active SKUs",
    stat_countries: "Countries Served",
    stat_accuracy: "Fulfillment Accuracy",
    trust_oem: "OEM Verified",
    trust_docs: "Export Docs & HS Code",
    trust_fast: "Fast Fulfillment",
    feature_shipping_title: "Global Shipping",
    feature_shipping_desc: "Export-ready logistics network reaching Asia, the Middle East, Africa, and beyond.",
    feature_genuine_title: "100% Genuine Parts",
    feature_genuine_desc: "OEM-certified parts with verifiable origin and consistent quality.",
    feature_inventory_title: "Large Inventory",
    feature_inventory_desc: "Extensive SKUs for Suzuki Genuine Parts plus Toyota, Daihatsu, and Mitsubishi.",
    feature_support_title: "Technical Support",
    feature_support_desc: "Assistance for fitment compatibility and part number cross-references.",
    batch_traceability: "Batch-level traceability",
    swipe_more: "Swipe to see more →",
    verified_partner: "Verified Partner",
    trusted_export_buyer: "Trusted export buyer",
  },
  id: {
    brand_line: "JMN • Distributor Resmi Suku Cadang Suzuki",
    hero_title: "Suku Cadang OEM Tepercaya untuk Indonesia & Dunia",
    hero_desc: "Kami PT. Jaya Makmur Nugraha (JMN) — distributor utama Suzuki Genuine Parts di Indonesia, juga memasok Toyota, Daihatsu, dan Mitsubishi.",
    browse_products: "Lihat Produk",
    get_quote: "Minta Penawaran",
    hero_search_placeholder: "Cari nomor part, model, atau kategori...",
    hero_search_button: "Cari",
    nav_products: "Produk",
    nav_why: "Mengapa Kami",
    nav_export: "Ekspor Global",
    nav_blog: "Blog",
    nav_contact: "Kontak",
    products_title: "Katalog Produk",
    products_sub: "Koleksi unggulan dari inventori multi-brand kami. Katalog lengkap tersedia atas permintaan.",
    quick_filters: "Filter",
    request_full_catalog: "Minta katalog lengkap",
    download_brochure: "Unduh brosur (PDF)",
    why_title: "Mengapa memilih JMN?",
    why_desc: "Sebagai distributor utama Suzuki Genuine Parts di Indonesia, kami memadukan hubungan OEM yang kuat dengan pemenuhan efisien dan kemampuan ekspor global.",
    export_title: "Kemampuan Ekspor Global",
    export_desc: "Kami kirim ke seluruh dunia dengan dokumen ekspor lengkap sesuai Incoterms Anda.",
    export_b1: "Konsolidasi multi-brand (Suzuki, Toyota, Daihatsu, Mitsubishi)",
    export_b2: "Opsi kargo udara & laut (LCL/FCL)",
    export_b3: "Proforma Invoice, Packing List, COO, dan dokumen ekspor lainnya",
    discuss_shipment: "Diskusikan pengiriman Anda",
    contact_title: "Hubungi Kami",
    contact_desc: "Sebutkan nomor part, kuantitas, tujuan, dan timeline. Balasan ≤ 1 hari kerja.",
    contact_name: "Nama Anda",
    contact_email: "Email",
    contact_message: "Pesan",
    contact_send: "Kirim via Email",
    contact_chat: "Chat di WhatsApp",
    faq_fast: "Data apa yang mempercepat penawaran?",
    faq_fast_a: "Nomor part (lebih baik OEM), model/tahun kendaraan, kuantitas, pelabuhan tujuan, Incoterms, dan lead time.",
    faq_ship: "Apakah bisa kirim internasional?",
    faq_ship_a: "Bisa — kami kirim global dengan dokumen ekspor dan beberapa forwarder (udara & laut).",
    faq_howbuy: "Bagaimana cara membeli spare part dari JMN?",
    faq_howbuy_a: "Kirimkan nomor part atau model kendaraan Anda via WhatsApp atau formulir kontak. Kami konfirmasi stok dan harga, terbitkan Proforma Invoice, lalu kirim setelah termin pembayaran disepakati.",
    faq_moq: "Apakah ada minimum order (MOQ) untuk ekspor?",
    faq_moq_a: "Kami melayani order percobaan dalam jumlah kecil maupun order ekspor kontainer penuh. Sampaikan target volume Anda dan kami akan sarankan opsi pengiriman paling efisien.",
    faq_countries: "Ekspor spare part ke negara mana saja?",
    faq_countries_a: "Kami rutin mengekspor Suzuki genuine parts ke Timur Tengah, Afrika, dan Asia Tenggara, dengan pengalaman pengiriman ke 22+ negara.",
    our_location: "Lokasi Kami",
    view_on_maps: "Lihat di Google Maps",
    testimonials_title: "Kata Mitra Kami",
    testimonials_sub: "Kisah nyata dari bengkel dan distributor yang memercayai JMN.",
    about_label: "Tentang Kami",
    product_label: "Katalog Produk",
    testimonials_label: "Testimoni",
    export_label: "Ekspor & Pengiriman",
    contact_label: "Hubungi Kami",
    location_label: "Lokasi Kami",
    export_lanes_title: "Rute ekspor tepercaya",
    hero_intro_cta: "Mengapa JMN?",
    stat_years: "Tahun Berdagang",
    stat_skus: "SKU Aktif",
    stat_countries: "Negara Terlayani",
    stat_accuracy: "Akurasi Pemenuhan",
    trust_oem: "OEM Terverifikasi",
    trust_docs: "Dokumen Ekspor & HS Code",
    trust_fast: "Pemenuhan Cepat",
    feature_shipping_title: "Pengiriman Global",
    feature_shipping_desc: "Jaringan logistik siap ekspor ke Asia, Timur Tengah, Afrika, dan wilayah lainnya.",
    feature_genuine_title: "100% Suku Cadang Asli",
    feature_genuine_desc: "Suku cadang bersertifikasi OEM dengan asal yang dapat diverifikasi dan kualitas konsisten.",
    feature_inventory_title: "Inventori Besar",
    feature_inventory_desc: "SKU luas untuk Suzuki Genuine Parts serta Toyota, Daihatsu, dan Mitsubishi.",
    feature_support_title: "Dukungan Teknis",
    feature_support_desc: "Bantuan kecocokan pemasangan dan referensi silang nomor part.",
    batch_traceability: "Traceability per batch",
    swipe_more: "Geser untuk lihat lainnya →",
    verified_partner: "Mitra Terverifikasi",
    trusted_export_buyer: "Pembeli ekspor tepercaya",
  },
  vi: {
    brand_line: "JMN • Nhà phân phối phụ tùng Suzuki chính hãng",
    hero_title: "Phụ tùng OEM đáng tin cậy cho Indonesia & Thế giới",
    hero_desc: "Chúng tôi là PT. Jaya Makmur Nugraha (JMN) — nhà phân phối chính phụ tùng Suzuki tại Indonesia, đồng thời cung cấp Toyota, Daihatsu và Mitsubishi.",
    browse_products: "Xem sản phẩm",
    get_quote: "Yêu cầu báo giá",
    hero_search_placeholder: "Tìm mã phụ tùng, mẫu xe hoặc danh mục...",
    hero_search_button: "Tìm kiếm",
    nav_products: "Sản phẩm",
    nav_why: "Vì sao chọn chúng tôi",
    nav_export: "Xuất khẩu",
    nav_blog: "Blog",
    nav_contact: "Liên hệ",
    products_title: "Danh mục sản phẩm",
    products_sub: "Các sản phẩm tiêu biểu trong kho đa thương hiệu. Danh mục đầy đủ theo yêu cầu.",
    quick_filters: "Bộ lọc",
    request_full_catalog: "Yêu cầu danh mục đầy đủ",
    download_brochure: "Tải brochure (PDF)",
    why_title: "Vì sao làm việc với JMN?",
    why_desc: "Là nhà phân phối chính phụ tùng Suzuki tại Indonesia, JMN có quan hệ OEM sâu rộng, thực hiện tinh gọn và năng lực xuất khẩu toàn cầu.",
    export_title: "Năng lực xuất khẩu toàn cầu",
    export_desc: "Chúng tôi giao hàng đi khắp thế giới với đầy đủ chứng từ theo Incoterms của bạn.",
    export_b1: "Hợp nhất đa thương hiệu (Suzuki, Toyota, Daihatsu, Mitsubishi)",
    export_b2: "Vận chuyển đường không & biển (LCL/FCL)",
    export_b3: "PI, Packing List, COO và chứng từ xuất khẩu khác",
    discuss_shipment: "Trao đổi lô hàng",
    contact_title: "Liên hệ",
    contact_desc: "Hãy cho chúng tôi mã phụ tùng, số lượng, điểm đến và thời gian. Chúng tôi phản hồi trong 1 ngày làm việc.",
    contact_name: "Tên của bạn",
    contact_email: "Email",
    contact_message: "Nội dung",
    contact_send: "Gửi Email",
    contact_chat: "Chat WhatsApp",
    faq_fast: "Thông tin nào giúp báo giá nhanh hơn?",
    faq_fast_a: "Mã phụ tùng, mẫu/năm xe, số lượng, cảng đến, Incoterms ưu tiên và thời gian giao hàng.",
    faq_ship: "Có giao quốc tế không?",
    faq_ship_a: "Có — chúng tôi giao toàn cầu với chứng từ xuất khẩu đầy đủ.",
    faq_howbuy: "Làm thế nào để mua phụ tùng từ JMN?",
    faq_howbuy_a: "Gửi cho chúng tôi mã phụ tùng hoặc mẫu xe qua WhatsApp hoặc biểu mẫu liên hệ. Chúng tôi xác nhận tồn kho và giá, phát hành Proforma Invoice, và giao hàng sau khi thống nhất điều khoản thanh toán.",
    faq_moq: "Có số lượng đặt hàng tối thiểu (MOQ) cho xuất khẩu không?",
    faq_moq_a: "Chúng tôi nhận cả đơn hàng thử nghiệm nhỏ và đơn hàng xuất khẩu nguyên container. Cho chúng tôi biết khối lượng mục tiêu để tư vấn phương án vận chuyển tối ưu.",
    faq_countries: "Xuất khẩu phụ tùng đến những quốc gia nào?",
    faq_countries_a: "Chúng tôi thường xuyên xuất khẩu phụ tùng chính hãng Suzuki đến Trung Đông, Châu Phi và Đông Nam Á, với kinh nghiệm giao hàng đến hơn 22 quốc gia.",
    our_location: "Địa chỉ của chúng tôi",
    view_on_maps: "Xem trên Google Maps",
    testimonials_title: "Khách hàng nói gì",
    testimonials_sub: "Câu chuyện thực từ các gara và nhà phân phối tin dùng JMN.",
    about_label: "Về chúng tôi",
    product_label: "Danh mục sản phẩm",
    testimonials_label: "Đánh giá",
    export_label: "Xuất khẩu & vận chuyển",
    contact_label: "Liên hệ",
    location_label: "Địa chỉ",
    export_lanes_title: "Tuyến xuất khẩu tin cậy",
    hero_intro_cta: "Vì sao chọn JMN?",
    stat_years: "Năm kinh doanh",
    stat_skus: "SKU đang hoạt động",
    stat_countries: "Quốc gia phục vụ",
    stat_accuracy: "Độ chính xác giao hàng",
    trust_oem: "OEM đã xác minh",
    trust_docs: "Chứng từ xuất khẩu & mã HS",
    trust_fast: "Thực hiện nhanh",
    feature_shipping_title: "Vận chuyển toàn cầu",
    feature_shipping_desc: "Mạng lưới logistics sẵn sàng xuất khẩu đến Châu Á, Trung Đông, Châu Phi và xa hơn.",
    feature_genuine_title: "100% phụ tùng chính hãng",
    feature_genuine_desc: "Phụ tùng đạt chuẩn OEM với nguồn gốc xác minh được và chất lượng ổn định.",
    feature_inventory_title: "Kho hàng lớn",
    feature_inventory_desc: "Nhiều SKU Suzuki Genuine Parts cùng Toyota, Daihatsu và Mitsubishi.",
    feature_support_title: "Hỗ trợ kỹ thuật",
    feature_support_desc: "Hỗ trợ kiểm tra tương thích lắp đặt và đối chiếu mã phụ tùng.",
    batch_traceability: "Truy xuất theo từng lô",
    swipe_more: "Vuốt để xem thêm →",
    verified_partner: "Đối tác đã xác minh",
    trusted_export_buyer: "Người mua xuất khẩu tin cậy",
  },
  ar: {
    brand_line: "جي إم إن • موزّع قطع سوزوكي الأصلية",
    hero_title: "قطع غيار OEM موثوقة لإندونيسيا والعالم",
    hero_desc: "نحن PT. Jaya Makmur Nugraha (JMN) — الموزع الرئيسي لقطع سوزوكي الأصلية في إندونيسيا ونزوّد أيضاً تويوتا ودايهاتسو وميتسوبيشي.",
    browse_products: "تصفح المنتجات",
    get_quote: "اطلب عرض سعر",
    hero_search_placeholder: "ابحث برقم القطعة أو الطراز أو الفئة...",
    hero_search_button: "بحث",
    nav_products: "المنتجات",
    nav_why: "لماذا نحن",
    nav_export: "التصدير العالمي",
    nav_blog: "المدونة",
    nav_contact: "تواصل معنا",
    products_title: "كتالوج المنتجات",
    products_sub: "تعرّف على أبرز منتجات مخزوننا متعدد العلامات. الكتالوج الكامل عند الطلب.",
    quick_filters: "فلاتر",
    request_full_catalog: "طلب الكتالوج الكامل",
    download_brochure: "تنزيل الكتيّب (PDF)",
    why_title: "لماذا العمل مع JMN؟",
    why_desc: "بصفتنا الموزّع الرئيسي لقطع سوزوكي في إندونيسيا، نجمع بين علاقات OEM عميقة وتنفيذ مرن وقدرات تصدير عالمية.",
    export_title: "قدرات التصدير العالمية",
    export_desc: "نرسل إلى جميع أنحاء العالم مع مستندات تصدير كاملة وفق Incoterms الخاصة بك.",
    export_b1: "تجميع متعدد العلامات (Suzuki وToyota وDaihatsu وMitsubishi)",
    export_b2: "الشحن الجوي والبحري (LCL/FCL)",
    export_b3: "فاتورة أولية وقائمة تعبئة وشهادة منشأ ومستندات أخرى",
    discuss_shipment: "ناقش شحنتك",
    contact_title: "تواصل معنا",
    contact_desc: "أرسل أرقام القطع والكميات والوجهة والمدة المطلوبة. سنرد خلال يوم عمل واحد.",
    contact_name: "اسمك",
    contact_email: "البريد الإلكتروني",
    contact_message: "الرسالة",
    contact_send: "إرسال عبر البريد",
    contact_chat: "الدردشة عبر واتساب",
    faq_fast: "ما المعلومات التي تساعدنا على التسعير أسرع؟",
    faq_fast_a: "أرقام القطع، طراز/سنة المركبة، الكميات، ميناء الوجهة، Incoterms، ووقت التسليم المطلوب.",
    faq_ship: "هل تشحنون دولياً؟",
    faq_ship_a: "نعم — نشحن عالمياً مع مستندات التصدير ووسطاء شحن متعددين.",
    faq_howbuy: "كيف يمكنني شراء قطع الغيار من JMN؟",
    faq_howbuy_a: "أرسل لنا أرقام القطع أو طراز المركبة عبر واتساب أو نموذج التواصل. نؤكد التوفر والسعر، ونصدر فاتورة أولية، ونشحن بعد الاتفاق على شروط الدفع.",
    faq_moq: "هل هناك حد أدنى للطلب (MOQ) للتصدير؟",
    faq_moq_a: "نستقبل الطلبات التجريبية الصغيرة وكذلك طلبات التصدير بحاوية كاملة. أخبرنا بحجمك المستهدف وسننصحك بأفضل خيار شحن من حيث التكلفة.",
    faq_countries: "إلى أي الدول تصدّرون قطع الغيار؟",
    faq_countries_a: "نصدّر بانتظام قطع سوزوكي الأصلية إلى الشرق الأوسط وأفريقيا وجنوب شرق آسيا، ولدينا خبرة في الشحن لأكثر من 22 دولة.",
    our_location: "موقعنا",
    view_on_maps: "عرض على خرائط Google",
    testimonials_title: "ماذا يقول شركاؤنا",
    testimonials_sub: "قصص حقيقية من ورش الإصلاح والموزعين الذين يثقون بـ JMN.",
    about_label: "من نحن",
    product_label: "كتالوج المنتجات",
    testimonials_label: "آراء العملاء",
    export_label: "التصدير والشحن",
    contact_label: "تواصل معنا",
    location_label: "موقعنا",
    export_lanes_title: "مسارات تصدير موثوقة",
    hero_intro_cta: "لماذا JMN؟",
    stat_years: "سنوات في التجارة",
    stat_skus: "رموز SKU نشطة",
    stat_countries: "دول نخدمها",
    stat_accuracy: "دقة التنفيذ",
    trust_oem: "OEM موثق",
    trust_docs: "مستندات تصدير ورمز HS",
    trust_fast: "تنفيذ سريع",
    feature_shipping_title: "شحن عالمي",
    feature_shipping_desc: "شبكة لوجستية جاهزة للتصدير تصل إلى آسيا والشرق الأوسط وأفريقيا وما بعدها.",
    feature_genuine_title: "قطع أصلية 100%",
    feature_genuine_desc: "قطع معتمدة من OEM بمنشأ قابل للتحقق وجودة ثابتة.",
    feature_inventory_title: "مخزون كبير",
    feature_inventory_desc: "تشكيلة واسعة من قطع Suzuki الأصلية إضافة إلى Toyota وDaihatsu وMitsubishi.",
    feature_support_title: "دعم فني",
    feature_support_desc: "مساعدة في توافق التركيب ومطابقة أرقام القطع البديلة.",
    batch_traceability: "تتبع على مستوى الدفعة",
    swipe_more: "← مرّر لمشاهدة المزيد",
    verified_partner: "شريك موثق",
    trusted_export_buyer: "مشتري تصدير موثوق",
  },
  th: {
    brand_line: "JMN • ผู้จัดจำหน่ายอะไหล่ Suzuki แท้",
    hero_title: "อะไหล่ OEM ที่เชื่อถือได้ สำหรับอินโดนีเซียและทั่วโลก",
    hero_desc: "เราเป็น PT. Jaya Makmur Nugraha (JMN) — ผู้จัดจำหน่ายหลักอะไหล่ Suzuki แท้ในอินโดนีเซีย และยังจำหน่าย Toyota, Daihatsu, Mitsubishi",
    browse_products: "ดูสินค้า",
    get_quote: "ขอใบเสนอราคา",
    hero_search_placeholder: "ค้นหาหมายเลขอะไหล่ รุ่นรถ หรือหมวดหมู่...",
    hero_search_button: "ค้นหา",
    nav_products: "สินค้า",
    nav_why: "ทำไมต้องเรา",
    nav_export: "การส่งออก",
    nav_blog: "บล็อก",
    nav_contact: "ติดต่อ",
    products_title: "แคตตาล็อกสินค้า",
    products_sub: "สินค้าเด่นจากคลังหลายแบรนด์ แคตตาล็อกฉบับเต็มมีให้ตามคำขอ",
    quick_filters: "ตัวกรอง",
    request_full_catalog: "ขอแคตตาล็อกฉบับเต็ม",
    download_brochure: "ดาวน์โหลดโบรชัวร์ (PDF)",
    why_title: "ทำไมต้องทำงานกับ JMN?",
    why_desc: "ในฐานะผู้จัดจำหน่ายหลักอะไหล่ Suzuki แท้ในอินโดนีเซีย เรามีความสัมพันธ์กับ OEM เข้มแข็ง พร้อมการส่งออกทั่วโลก",
    export_title: "ศักยภาพการส่งออกระดับโลก",
    export_desc: "เราจัดส่งทั่วโลก พร้อมเอกสารการส่งออกครบถ้วนตาม Incoterms ของคุณ",
    export_b1: "รวมหลายแบรนด์ (Suzuki, Toyota, Daihatsu, Mitsubishi)",
    export_b2: "ขนส่งทางอากาศ/ทางเรือ (LCL/FCL)",
    export_b3: "PI, Packing List, COO และเอกสารอื่น ๆ",
    discuss_shipment: "คุยรายละเอียดการส่งออก",
    contact_title: "ติดต่อเรา",
    contact_desc: "บอกหมายเลขอะไหล่ ปริมาณ ปลายทาง และระยะเวลา ทีมขายตอบกลับภายใน 1 วันทำการ",
    contact_name: "ชื่อของคุณ",
    contact_email: "อีเมล",
    contact_message: "ข้อความ",
    contact_send: "ส่งอีเมล",
    contact_chat: "แชทผ่าน WhatsApp",
    faq_fast: "ข้อมูลใดช่วยให้เสนอราคาเร็วขึ้น?",
    faq_fast_a: "หมายเลขอะไหล่ รุ่น/ปีรถ ปริมาณ ท่าเรือปลายทาง Incoterms และเวลาจัดส่งที่ต้องการ",
    faq_ship: "มีจัดส่งระหว่างประเทศหรือไม่?",
    faq_ship_a: "มี — เราจัดส่งทั่วโลกพร้อมเอกสารส่งออกครบถ้วน",
    faq_howbuy: "จะสั่งซื้ออะไหล่จาก JMN ได้อย่างไร?",
    faq_howbuy_a: "ส่งหมายเลขอะไหล่หรือรุ่นรถของคุณผ่าน WhatsApp หรือแบบฟอร์มติดต่อ เรายืนยันสต็อกและราคา ออกใบ Proforma Invoice และจัดส่งหลังตกลงเงื่อนไขการชำระเงิน",
    faq_moq: "มีจำนวนสั่งซื้อขั้นต่ำ (MOQ) สำหรับการส่งออกหรือไม่?",
    faq_moq_a: "เรารับทั้งคำสั่งซื้อทดลองจำนวนน้อยและคำสั่งซื้อส่งออกแบบเต็มตู้คอนเทนเนอร์ แจ้งปริมาณเป้าหมายของคุณ เราจะแนะนำวิธีจัดส่งที่คุ้มค่าที่สุด",
    faq_countries: "ส่งออกอะไหล่ไปประเทศใดบ้าง?",
    faq_countries_a: "เราส่งออกอะไหล่แท้ Suzuki เป็นประจำไปยังตะวันออกกลาง แอฟริกา และเอเชียตะวันออกเฉียงใต้ มีประสบการณ์จัดส่งไปแล้วกว่า 22 ประเทศ",
    our_location: "ที่ตั้งของเรา",
    view_on_maps: "ดูบน Google Maps",
    testimonials_title: "เสียงจากพาร์ทเนอร์",
    testimonials_sub: "เรื่องจริงจากอู่และผู้จัดจำหน่ายที่ไว้วางใจ JMN",
    about_label: "เกี่ยวกับเรา",
    product_label: "แคตตาล็อกสินค้า",
    testimonials_label: "คำรับรอง",
    export_label: "ส่งออกและขนส่ง",
    contact_label: "ติดต่อเรา",
    location_label: "ที่ตั้งของเรา",
    export_lanes_title: "เส้นทางส่งออกที่เชื่อถือได้",
    hero_intro_cta: "ทำไมต้อง JMN?",
    stat_years: "ปีในธุรกิจ",
    stat_skus: "SKU ที่พร้อมจำหน่าย",
    stat_countries: "ประเทศที่ให้บริการ",
    stat_accuracy: "ความแม่นยำในการจัดส่ง",
    trust_oem: "ยืนยัน OEM",
    trust_docs: "เอกสารส่งออกและ HS Code",
    trust_fast: "จัดส่งรวดเร็ว",
    feature_shipping_title: "การขนส่งทั่วโลก",
    feature_shipping_desc: "เครือข่ายโลจิสติกส์พร้อมส่งออกสู่เอเชีย ตะวันออกกลาง แอฟริกา และภูมิภาคอื่น ๆ",
    feature_genuine_title: "อะไหล่แท้ 100%",
    feature_genuine_desc: "อะไหล่มาตรฐาน OEM พร้อมแหล่งที่มาตรวจสอบได้และคุณภาพสม่ำเสมอ",
    feature_inventory_title: "สต็อกขนาดใหญ่",
    feature_inventory_desc: "SKU จำนวนมากสำหรับ Suzuki Genuine Parts รวมถึง Toyota, Daihatsu และ Mitsubishi",
    feature_support_title: "การสนับสนุนทางเทคนิค",
    feature_support_desc: "ช่วยตรวจสอบความเข้ากันได้และการเทียบหมายเลขอะไหล่",
    batch_traceability: "ตรวจสอบย้อนกลับตามล็อต",
    swipe_more: "ปัดเพื่อดูเพิ่มเติม →",
    verified_partner: "พาร์ทเนอร์ที่ยืนยันแล้ว",
    trusted_export_buyer: "ผู้ซื้อส่งออกที่เชื่อถือได้",
  },
} as const;

export const useT = () => {
  const lang = React.useContext(LangContext);
  return (k: keyof typeof STR["en"]) =>
    STR[lang]?.[k] ?? STR.en[k] ?? String(k);
};

export { DEFAULT_LANG, LANGS };
